# This is the main configuration file for the MkDocs website.
# Use hash-comments to comment out pages have not been written
# Reference: http://www.mkdocs.org/user-guide/configuration/
#
site_name: GeoProcessor
nav:
- Home: index.md
- Introduction: introduction/introduction.md
- Getting Started: getting-started/getting-started.md
- Running the GeoProcessor:
  - Overview: running/overview.md
  - User Interface (UI): running/ui.md
  - Command Line (Batch): running/cl-batch.md
  - Command Line (Interpreter): running/cl-interpreter.md
  - Testing Framework (Batch & UI): running/gptest.md
- Best Practices:
  - Command Files: best-practices/command-files.md
  - GeoLayer Identifiers: best-practices/geolayer-identifiers.md
  - Table Identifiers: best-practices/table-identifiers.md
- Troubleshooting: troubleshooting/troubleshooting.md
- Reference - Commands:
  - Overview: command-ref/overview.md
  - AddGeoLayerAttribute: command-ref/AddGeoLayerAttribute/AddGeoLayerAttribute.md
  - AddGeoLayerViewGroupToGeoMap: command-ref/AddGeoLayerViewGroupToGeoMap/AddGeoLayerViewGroupToGeoMap.md
  - AddGeoLayerViewToGeoMap: command-ref/AddGeoLayerViewToGeoMap/AddGeoLayerViewToGeoMap.md
  - AddGeoMapToGeoMapProject: command-ref/AddGeoMapToGeoMapProject/AddGeoMapToGeoMapProject.md
  - Blank: command-ref/Blank/Blank.md  
  - ChangeGeoLayerGeometry: command-ref/ChangeGeoLayerGeometry/ChangeGeoLayerGeometry.md
  - ChangeRasterGeoLayerCRS: command-ref/ChangeRasterGeoLayerCRS/ChangeRasterGeoLayerCRS.md
  - ClipGeoLayer: command-ref/ClipGeoLayer/ClipGeoLayer.md
  - CloseDataStore: command-ref/CloseDataStore/CloseDataStore.md
  - Comment: command-ref/Comment/Comment.md
  - CommentBlockEnd: command-ref/CommentBlockEnd/CommentBlockEnd.md
  - CommentBlockStart: command-ref/CommentBlockStart/CommentBlockStart.md
  - CompareFiles: command-ref/CompareFiles/CompareFiles.md
  - CopyFile: command-ref/CopyFile/CopyFile.md
  - CopyGeoLayer: command-ref/CopyGeoLayer/CopyGeoLayer.md
  - CreateFolder: command-ref/CreateFolder/CreateFolder.md
  - CreateGeoLayerFromGeometry: command-ref/CreateGeoLayerFromGeometry/CreateGeoLayerFromGeometry.md
  - CreateGeoMap: command-ref/CreateGeoMap/CreateGeoMap.md
  - CreateGeoMapProject: command-ref/CreateGeoMapProject/CreateGeoMapProject.md
  - CreateRasterGeoLayer: command-ref/CreateRasterGeoLayer/CreateRasterGeoLayer.md
  - CreateRegressionTestCommandFile: command-ref/CreateRegressionTestCommandFile/CreateRegressionTestCommandFile.md
  - EndFor: command-ref/EndFor/EndFor.md
  - EndIf: command-ref/EndIf/EndIf.md
  - Exit: command-ref/Exit/Exit.md
  - FixGeoLayer: command-ref/FixGeoLayer/FixGeoLayer.md
  - For: command-ref/For/For.md
  - FreeGeoLayers: command-ref/FreeGeoLayers/FreeGeoLayers.md  
  - FTPGet: command-ref/FTPGet/FTPGet.md
  - If: command-ref/If/If.md
  - IntersectGeoLayer: command-ref/IntersectGeoLayer/IntersectGeoLayer.md
  - ListFiles: command-ref/ListFiles/ListFiles.md
  - MergeGeoLayers: command-ref/MergeGeoLayers/MergeGeoLayers.md
  - Message: command-ref/Message/Message.md
  - OpenDataStore: command-ref/OpenDataStore/OpenDataStore.md
  - QgisAlgorithmHelp: command-ref/QgisAlgorithmHelp/QgisAlgorithmHelp.md
  - RasterizeGeoLayer: command-ref/RasterizeGeoLayer/RasterizeGeoLayer.md
  - ReadGeoLayerFromDelimitedFile: command-ref/ReadGeoLayerFromDelimitedFile/ReadGeoLayerFromDelimitedFile.md
  - ReadGeoLayerFromGeoJSON: command-ref/ReadGeoLayerFromGeoJSON/ReadGeoLayerFromGeoJSON.md
  - ReadGeoLayerFromKML: command-ref/ReadGeoLayerFromKML/ReadGeoLayerFromKML.md
  - ReadGeoLayerFromShapefile: command-ref/ReadGeoLayerFromShapefile/ReadGeoLayerFromShapefile.md
  - ReadGeoLayerFromWebFeatureService: command-ref/ReadGeoLayerFromWebFeatureService/ReadGeoLayerFromWebFeatureService.md
  - ReadGeoLayersFromFGDB: command-ref/ReadGeoLayersFromFGDB/ReadGeoLayersFromFGDB.md
  - ReadGeoLayersFromFolder: command-ref/ReadGeoLayersFromFolder/ReadGeoLayersFromFolder.md
  - ReadGeoLayersFromGeoPackage: command-ref/ReadGeoLayersFromGeoPackage/ReadGeoLayersFromGeoPackage.md
  - ReadRasterGeoLayerFromFile: command-ref/ReadRasterGeoLayerFromFile/ReadRasterGeoLayerFromFile.md
  - ReadRasterGeoLayerFromTileMapService: command-ref/ReadRasterGeoLayerFromTileMapService/ReadRasterGeoLayerFromTileMapService.md
  - ReadRasterGeoLayerFromWebMapService: command-ref/ReadRasterGeoLayerFromWebMapService/ReadRasterGeoLayerFromWebMapService.md
  - ReadTableFromDataStore: command-ref/ReadTableFromDataStore/ReadTableFromDataStore.md
  - ReadTableFromDelimitedFile: command-ref/ReadTableFromDelimitedFile/ReadTableFromDelimitedFile.md
  - ReadTableFromExcel: command-ref/ReadTableFromExcel/ReadTableFromExcel.md
  - RearrangeRasterGeoLayerBands: command-ref/RearrangeRasterGeoLayerBands/RearrangeRasterGeoLayerBands.md
  - RemoveFile: command-ref/RemoveFile/RemoveFile.md
  - RemoveGeoLayerAttributes: command-ref/RemoveGeoLayerAttributes/RemoveGeoLayerAttributes.md
  - RenameGeoLayerAttribute: command-ref/RenameGeoLayerAttribute/RenameGeoLayerAttribute.md
  - RemoveGeoLayerFeatures: command-ref/RemoveGeoLayerFeatures/RemoveGeoLayerFeatures.md
  - RunCommands: command-ref/RunCommands/RunCommands.md
  - RunGdalProgram: command-ref/RunGdalProgram/RunGdalProgram.md
  - RunOgrProgram: command-ref/RunOgrProgram/RunOgrProgram.md
  - RunProgram: command-ref/RunProgram/RunProgram.md
  - RunSql: command-ref/RunSql/RunSql.md
  - SetGeoLayerCRS: command-ref/SetGeoLayerCRS/SetGeoLayerCRS.md
  - SetGeoLayerProperty: command-ref/SetGeoLayerProperty/SetGeoLayerProperty.md  
  - SetGeoLayerViewCategorizedSymbol: command-ref/SetGeoLayerViewCategorizedSymbol/SetGeoLayerViewCategorizedSymbol.md
  - SetGeoLayerViewEventHandler: command-ref/SetGeoLayerViewEventHandler/SetGeoLayerViewEventHandler.md
  - SetGeoLayerViewGraduatedSymbol`: command-ref/SetGeoLayerViewGraduatedSymbol/SetGeoLayerViewGraduatedSymbol.md
  - SetGeoLayerViewSingleSymbol: command-ref/SetGeoLayerViewSingleSymbol/SetGeoLayerViewSingleSymbol.md
  - SetProperty: command-ref/SetProperty/SetProperty.md
  - SetPropertyFromGeoLayer: command-ref/SetPropertyFromGeoLayer/SetPropertyFromGeoLayer.md
  - SimplifyGeoLayerGeometry: command-ref/SimplifyGeoLayerGeometry/SimplifyGeoLayerGeometry.md  
  - SplitGeoLayerByAttribute: command-ref/SplitGeoLayerByAttribute/SplitGeoLayerByAttribute.md  
  - StartLog: command-ref/StartLog/StartLog.md
  - StartRegressionTestResultsReport: command-ref/StartRegressionTestResultsReport/StartRegressionTestResultsReport.md
  - UnknownCommand: command-ref/UnknownCommand/UnknownCommand.md
  - UnzipFile: command-ref/UnzipFile/UnzipFile.md
  - WebGet: command-ref/WebGet/WebGet.md
  - WriteCommandSummaryToFile: command-ref/WriteCommandSummaryToFile/WriteCommandSummaryToFile.md
  - WriteGeoLayerPropertiesToFile: command-ref/WriteGeoLayerPropertiesToFile/WriteGeoLayerPropertiesToFile.md
  - WriteGeoLayerToDelimitedFile: command-ref/WriteGeoLayerToDelimitedFile/WriteGeoLayerToDelimitedFile.md
  - WriteGeoLayerToGeoJSON: command-ref/WriteGeoLayerToGeoJSON/WriteGeoLayerToGeoJSON.md
  - WriteGeoLayerToKML: command-ref/WriteGeoLayerToKML/WriteGeoLayerToKML.md
  - WriteGeoLayerToShapefile: command-ref/WriteGeoLayerToShapefile/WriteGeoLayerToShapefile.md
  - WriteGeoMapProjectToJSON: command-ref/WriteGeoMapProjectToJSON/WriteGeoMapProjectToJSON.md
  - WritePropertiesToFile: command-ref/WritePropertiesToFile/WritePropertiesToFile.md
  - WriteRasterGeoLayerToFile: command-ref/WriteRasterGeoLayerToFile/WriteRasterGeoLayerToFile.md
  - WriteTableToDataStore: command-ref/WriteTableToDataStore/WriteTableToDataStore.md
  - WriteTableToDelimitedFile: command-ref/WriteTableToDelimitedFile/WriteTableToDelimitedFile.md
  - WriteTableToExcel: command-ref/WriteTableToExcel/WriteTableToExcel.md  
- Reference - Datastores and Spatial Data Formats:
  - Overview: spatial-data-format-ref/overview.md
  - Esri File Geodatabase: spatial-data-format-ref/EsriFileGeodatabase/EsriFileGeodatabase.md
  - Esri Shapefile: spatial-data-format-ref/EsriShapefile/EsriShapefile.md
  - Esri WFS: spatial-data-format-ref/EsriWFS/EsriWFS.md
  - GeoJSON: spatial-data-format-ref/GeoJSON/GeoJSON.md
  - GeoPackage: spatial-data-format-ref/GeoPackage/GeoPackage.md
  - GeoTIFF: spatial-data-format-ref/GeoTIFF/GeoTIFF.md
  - KML: spatial-data-format-ref/KML/KML.md
  - OGS WMTS: spatial-data-format-ref/OGC-WMTS/OGC-WMTS.md
- Reference - Resources: resources/resources.md
- Appendix - Installing: appendix-install/install.md
- Appendix - GeoMapProject: appendix-geomapproject/geomapproject.md
- Appendix - Release Notes:
  - Release Notes: appendix-release-notes/release-notes.md
  - Version 1: appendix-release-notes/release-notes-1.md
# ------- configuration properties ---------------
# Alphabetize
# ------------------------------------------------
copyright:  Copyright Open Water Foundation
# ------------------------------------------------
# Use extra CSS to customize styles, based on theme
extra_css:
  - 'css/extra-material-theme.css'
# ------------------------------------------------
# Google Analytics
# - see:  https://squidfunk.github.io/mkdocs-material/getting-started/#google-analytics
google_analytics:
 - 'UA-135465513-1'
 - auto
# ------------------------------------------------
markdown_extensions:
  - footnotes
# ------------------------------------------------
# Favicon is supposed to automatically be found:
# - in docs/img/favicon.ico
# - is a copy of docs/images/OWF-Logo-Favicon-32x32.ico
# - instead, with Material them, have a different approach (see "theme" below)
# ------------------------------------------------
# Don't enable the repo URL because irritating edit icons are shown when editing really isn't allowed
#repo_url:  https://github.com/OpenWaterFoundation/owf-app-geoprocessor-python-doc-user
# ------------------------------------------------
site_author:  Open Water Foundation
site_description:  Open Water Foundation GeoProcessor
# ------------------------------------------------
# Use Material theme
# - installation notes:  https://github.com/squidfunk/mkdocs-material
theme:
  name: material
  favicon:  'img/favicon.ico'
# ------------------------------------------------
# The following controls how URLs are created
# - As of MkDocs 1.0 the default is true meaning URLs to a page ABC is ABC/ rather than something/ABC.html.
# - see:  https://www.mkdocs.org/user-guide/configuration/#use_directory_urls
# use_directory_urls: true
# ------------------------------------------------
