# This is the main configuration file for the MkDocs website.
# Use hash-comments to comment out pages have not been written
# Reference: http://www.mkdocs.org/user-guide/configuration/
#
site_name: Learn / OWF GeoProcessor
pages:
- Home: index.md
- Introduction: introduction.md
- Install GeoProcessor: install.md
- Getting Started: getting-started.md
- Command Reference:
  - Overview: command-ref/overview.md
  - CompareFiles: command-ref/CompareFiles/CompareFiles.md
  - CopyFile: command-ref/CopyFile/CopyFile.md
  - EndFor: command-ref/EndFor/EndFor.md
  - EndIf: command-ref/EndIf/EndIf.md
  - For: command-ref/For/For.md
  - If: command-ref/If/If.md
  - Message: command-ref/Message/Message.md
  - ReadGeoLayerFromGeoJSON: command-ref/ReadGeoLayerFromGeoJSON/ReadGeoLayerFromGeoJSON.md
  - ReadGeoLayerFromShapefile: command-ref/ReadGeoLayerFromShapefile/ReadGeoLayerFromShapefile.md
  - ReadGeoLayersFromFolder: command-ref/ReadGeoLayersFromFolder/ReadGeoLayersFromFolder.md
  - ReadGeoLayersFromFGDB: command-ref/ReadGeoLayersFromFGDB/ReadGeoLayersFromFGDB.md
  - RemoveFile: command-ref/RemoveFile/RemoveFile.md
  - SetProperty: command-ref/SetProperty/SetProperty.md
  - StartLog: command-ref/StartLog/StartLog.md
  - WriteGeoLayerToGeoJSON: command-ref/WriteGeoLayerToGeoJSON/WriteGeoLayerToGeoJSON.md
  - WriteGeolayerToShapefile: command-ref/WriteGeoLayerToShapefile/WriteGeolayerToShapefile.md
- Spatial Data Format Reference:
  - Overview: spatial-data-format-ref/overview.md
  - Esri File Geodatabase: spatial-data-format-ref/EsriFileGeodatabase/EsriFileGeodatabase.md
  - Esri Shapefile: spatial-data-format-ref/EsriShapefile/EsriShapefile.md
  - GeoJSON: spatial-data-format-ref/GeoJSON/GeoJSON.md
- Input Formatting Reference:
  - Overview: input-formatting-ref/overview.md
  - ${Property} Syntax: input-formatting-ref/$property-syntax/$property-syntax.md
  - Formatting Characters: input-formatting-ref/formatting-characters/formatting-characters.md
- Resources: resources.md
- Troubleshooting: troubleshooting.md
# ------- configuration properties ---------------
# Use Material theme
# - installation notes:  https://github.com/squidfunk/mkdocs-material
theme: material
repo_url:  https://github.com/OpenWaterFoundation/owf-app-geoprocessor-python-doc-user
site_description:  Open Water Foundation Learn GeoProcessor
site_author:  Open Water Foundation
site_favicon:  'images/OWF-Logo-Favicon-32x32.png'
copyright:  Copyright Open Water Foundation
# Use extra CSS to customize styles, based on theme
extra_css:
  - 'css/extra-material-theme.css'
markdown_extensions:
  - footnotes
