# This is the main configuration file for the MkDocs website.
# Use hash-comments to comment out pages have not been written
# Reference: http://www.mkdocs.org/user-guide/configuration/
#
site_name: Learn / OWF GeoProcessor
pages:
- Home: index.md
- Introduction: introduction.md
- Install GeoProcessor: install.md
- Getting Started: getting-started.md
- Command Reference:
  - Overview: command-ref/overview.md
  - Spatial Data Layers:
    - AddGeoLayerAttribute: command-ref/AddGeoLayerAttribute/AddGeoLayerAttribute.md
    - ClipGeoLayer: command-ref/ClipGeoLayer/ClipGeoLayer.md
    - CopyGeoLayer: command-ref/CopyGeoLayer/CopyGeoLayer.md
    - CreateGeoLayerFromGeometry: command-ref/CreateGeoLayerFromGeometry/CreateGeoLayerFromGeometry.md
    - FreeGeoLayers: command-ref/FreeGeoLayers/FreeGeoLayers.md  
    - IntersectGeoLayer: command-ref/IntersectGeoLayer/IntersectGeoLayer.md
    - MergeGeoLayers: command-ref/MergeGeoLayers/MergeGeoLayers.md  
    - ReadGeoLayerFromDelimitedFile: command-ref/ReadGeoLayerFromDelimitedFile/ReadGeoLayerFromDelimitedFile.md
    - ReadGeoLayerFromGeoJSON: command-ref/ReadGeoLayerFromGeoJSON/ReadGeoLayerFromGeoJSON.md
    - ReadGeoLayerFromShapefile: command-ref/ReadGeoLayerFromShapefile/ReadGeoLayerFromShapefile.md
    - ReadGeoLayersFromFGDB: command-ref/ReadGeoLayersFromFGDB/ReadGeoLayersFromFGDB.md
    - ReadGeoLayersFromFolder: command-ref/ReadGeoLayersFromFolder/ReadGeoLayersFromFolder.md
    - RemoveGeoLayerAttributes: command-ref/RemoveGeoLayerAttributes/RemoveGeoLayerAttributes.md
    - RenameGeoLayerAttribute: command-ref/RenameGeoLayerAttribute/RenameGeoLayerAttribute.md
    - SetGeoLayerCRS: command-ref/SetGeoLayerCRS/SetGeoLayerCRS.md
    - SetGeoLayerProperty: command-ref/SetGeoLayerProperty/SetGeoLayerProperty.md  
    - SimplifyGeoLayerGeometry: command-ref/SimplifyGeoLayerGeometry/SimplifyGeoLayerGeometry.md  
    - WriteGeoLayerToDelimitedFile: command-ref/WriteGeoLayerToDelimitedFile/WriteGeoLayerToDelimitedFile.md
    - WriteGeoLayerToGeoJSON: command-ref/WriteGeoLayerToGeoJSON/WriteGeoLayerToGeoJSON.md
    - WriteGeoLayerToKML: command-ref/WriteGeoLayerToKML/WriteGeoLayerToKML.md
    - WriteGeoLayerToShapefile: command-ref/WriteGeoLayerToShapefile/WriteGeolayerToShapefile.md
  - Tabular Data:
    - OpenDataStore: command-ref/OpenDataStore/OpenDataStore.md
    - ReadTableFromDataStore: command-ref/ReadTableFromDataStore/ReadTableFromDataStore.md
    - ReadTableFromDelimitedFile: command-ref/ReadTableFromDelimitedFile/ReadTableFromDelimitedFile.md
    - ReadTableFromExcel: command-ref/ReadTableFromExcel/ReadTableFromExcel.md
    - WriteTableToDataStore: command-ref/WriteTableToDataStore/WriteTableToDataStore.md
    - WriteTableToDelimitedFile: command-ref/WriteTableToDelimitedFile/WriteTableToDelimitedFile.md
    - WriteTableToExcel: command-ref/WriteTableToExcel/WriteTableToExcel.md
  - Control Running: 
    - EndFor: command-ref/EndFor/EndFor.md
    - EndIf: command-ref/EndIf/EndIf.md
    - For: command-ref/For/For.md
    - If: command-ref/If/If.md
    - RunProgram: command-ref/RunProgram/RunProgram.md
    - SetProperty: command-ref/SetProperty/SetProperty.md
    - SetPropertyFromGeoLayer: command-ref/SetPropertyFromGeoLayer/SetPropertyFromGeoLayer.md
  - Utility:
    - Blank: command-ref/Blank/Blank.md  
    - Comment: command-ref/Comment/Comment.md
    - CommentBlockStart: command-ref/CommentBlockStart/CommentBlockStart.md
    - CommentBlockEnd: command-ref/CommentBlockEnd/CommentBlockEnd.md
    - UnknownCommand: command-ref/UnknownCommand/UnknownCommand.md
  - Testing:
    - CompareFiles: command-ref/CompareFiles/CompareFiles.md
    - CreateRegressionTestCommandFile: command-ref/CreateRegressionTestCommandFile/CreateRegressionTestCommandFile.md
    - RunCommands: command-ref/RunCommands/RunCommands.md
    - StartRegressionTestResultsReport: command-ref/StartRegressionTestResultsReport/StartRegressionTestResultsReport.md
    - WriteCommandSummaryToFile: command-ref/WriteCommandSummaryToFile/WriteCommandSummaryToFile.md
    - WriteGeoLayerPropertiesToFile: command-ref/WriteGeoLayerPropertiesToFile/WriteGeoLayerPropertiesToFile.md
    - WritePropertiesToFile: command-ref/WritePropertiesToFile/WritePropertiesToFile.md
  - Handling Files:
    - CopyFile: command-ref/CopyFile/CopyFile.md
    - ListFiles: command-ref/ListFiles/ListFiles.md
    - RemoveFile: command-ref/RemoveFile/RemoveFile.md
    - UnzipFile: command-ref/UnzipFile/UnzipFile.md
    - WebGet: command-ref/WebGet/WebGet.md
  - Messages and Logging:
    - Message: command-ref/Message/Message.md
    - StartLog: command-ref/StartLog/StartLog.md  
- Spatial Data Format Reference:
  - Overview: spatial-data-format-ref/overview.md
  - Esri File Geodatabase: spatial-data-format-ref/EsriFileGeodatabase/EsriFileGeodatabase.md
  - Esri Shapefile: spatial-data-format-ref/EsriShapefile/EsriShapefile.md
  - GeoJSON: spatial-data-format-ref/GeoJSON/GeoJSON.md
  - KML: spatial-data-format-ref/KML/KML.md
- Best Practices:
  - GeoLayer Identifiers: best-practices/geolayer-identifiers.md
  - Table Identifiers: best-practices/table-identifiers.md
- Resources: resources.md
- Troubleshooting: troubleshooting.md
# ------- configuration properties ---------------
# Use Material theme
# - installation notes:  https://github.com/squidfunk/mkdocs-material
theme: material
# Don't enable the repo URL because irritating edit icons are shown when editing really isn't allowed
#repo_url:  https://github.com/OpenWaterFoundation/owf-app-geoprocessor-python-doc-user
site_description:  Open Water Foundation Learn GeoProcessor
site_author:  Open Water Foundation
site_favicon:  'images/OWF-Logo-Favicon-32x32.png'
copyright:  Copyright Open Water Foundation
# Use extra CSS to customize styles, based on theme
extra_css:
  - 'css/extra-material-theme.css'
markdown_extensions:
  - footnotes
