# This is the main configuration file for the MkDocs website.
# Use hash-comments to comment out pages have not been written
# Reference: http://www.mkdocs.org/user-guide/configuration/
#
site_name: Learn / OWF GeoProcessor
pages:
- Home: index.md
- Introduction: introduction.md
- Install GeoProcessor: install.md
- Getting Started: getting-started.md
- Command Reference:
  - Overview: command-ref/overview.md
  - AddGeoLayerAttribute: command-ref/AddGeoLayerAttribute/AddGeoLayerAttribute.md
  - Blank: command-ref/Blank/Blank.md
  - ClipGeoLayer: command-ref/ClipGeoLayer/ClipGeoLayer.md
  - Comment: command-ref/Comment/Comment.md
  - CommentBlockStart: command-ref/CommentBlockStart/CommentBlockStart.md
  - CommentBlockEnd: command-ref/CommentBlockEnd/CommentBlockEnd.md
  - CompareFiles: command-ref/CompareFiles/CompareFiles.md
  - CopyFile: command-ref/CopyFile/CopyFile.md
  - CopyGeoLayer: command-ref/CopyGeoLayer/CopyGeoLayer.md
  - CreateGeoLayerFromGeometry: command-ref/CreateGeoLayerFromGeometry/CreateGeoLayerFromGeometry.md
  - CreateRegressionTestCommandFile: command-ref/CreateRegressionTestCommandFile/CreateRegressionTestCommandFile.md
  - EndFor: command-ref/EndFor/EndFor.md
  - EndIf: command-ref/EndIf/EndIf.md
  - For: command-ref/For/For.md
  - FreeGeoLayers: command-ref/FreeGeoLayers/FreeGeoLayers.md
  - If: command-ref/If/If.md
  - IntersectGeoLayer: command-ref/IntersectGeoLayer/IntersectGeoLayer.md
  - ListFiles: command-ref/ListFiles/ListFiles.md
  - MergeGeoLayers: command-ref/MergeGeoLayers/MergeGeoLayers.md
  - Message: command-ref/Message/Message.md
  - ReadGeoLayerFromDelimitedFile: command-ref/ReadGeoLayerFromDelimitedFile/ReadGeoLayerFromDelimitedFile.md
  - ReadGeoLayerFromFGDB: command-ref/ReadGeoLayerFromFGDB/ReadGeoLayerFromFGDB.md
  - ReadGeoLayerFromGeoJSON: command-ref/ReadGeoLayerFromGeoJSON/ReadGeoLayerFromGeoJSON.md
  - ReadGeoLayerFromShapefile: command-ref/ReadGeoLayerFromShapefile/ReadGeoLayerFromShapefile.md
  - ReadGeoLayersFromFGDB: command-ref/ReadGeoLayersFromFGDB/ReadGeoLayersFromFGDB.md
  - ReadGeoLayersFromFolder: command-ref/ReadGeoLayersFromFolder/ReadGeoLayersFromFolder.md
  - ReadTableFromExcel: command-ref/ReadTableFromExcel/ReadTableFromExcel.md
  - RemoveFile: command-ref/RemoveFile/RemoveFile.md
  - RemoveGeoLayerAttributes: command-ref/RemoveGeoLayerAttributes/RemoveGeoLayerAttributes.md
  - RenameGeoLayerAttribute: command-ref/RenameGeoLayerAttribute/RenameGeoLayerAttribute.md
  - RunCommands: command-ref/RunCommands/RunCommands.md
  - RunProgram: command-ref/RunProgram/RunProgram.md
  - SetGeoLayerCRS: command-ref/SetGeoLayerCRS/SetGeoLayerCRS.md
  - SetGeoLayerProperty: command-ref/SetGeoLayerProperty/SetGeoLayerProperty.md
  - SetProperty: command-ref/SetProperty/SetProperty.md
  - SetPropertyFromGeoLayer: command-ref/SetPropertyFromGeoLayer/SetPropertyFromGeoLayer.md
  - SimplifyGeoLayerGeometry: command-ref/SimplifyGeoLayerGeometry/SimplifyGeoLayerGeometry.md
  - StartLog: command-ref/StartLog/StartLog.md
  - StartRegressionTestResultsReport: command-ref/StartRegressionTestResultsReport/StartRegressionTestResultsReport.md
  - UnknownCommand: command-ref/UnknownCommand/UnknownCommand.md
  - UnzipFile: command-ref/UnzipFile/UnzipFile.md
  - WebGet: command-ref/WebGet/WebGet.md
  - WriteCommandSummaryToFile: command-ref/WriteCommandSummaryToFile/WriteCommandSummaryToFile.md
  - WriteGeoLayerPropertiesToFile: command-ref/WriteGeoLayerPropertiesToFile/WriteGeoLayerPropertiesToFile.md
  - WriteGeoLayerToDelimitedFile: command-ref/WriteGeoLayerToDelimitedFile/WriteGeoLayerToDelimitedFile.md
  - WriteGeoLayerToGeoJSON: command-ref/WriteGeoLayerToGeoJSON/WriteGeoLayerToGeoJSON.md
  - WriteGeoLayerToKML: command-ref/WriteGeoLayerToKML/WriteGeoLayerToKML.md
  - WriteGeoLayerToShapefile: command-ref/WriteGeoLayerToShapefile/WriteGeolayerToShapefile.md
  - WriteTableToExcel: command-ref/WriteTableToExcel/WriteTableToExcel.md
  - WritePropertiesToFile: command-ref/WritePropertiesToFile/WritePropertiesToFile.md
- Spatial Data Format Reference:
  - Overview: spatial-data-format-ref/overview.md
  - Esri File Geodatabase: spatial-data-format-ref/EsriFileGeodatabase/EsriFileGeodatabase.md
  - Esri Shapefile: spatial-data-format-ref/EsriShapefile/EsriShapefile.md
  - GeoJSON: spatial-data-format-ref/GeoJSON/GeoJSON.md
  - KML: spatial-data-format-ref/KML/KML.md
- Best Practices:
  - GeoLayer Identifiers: best-practices/geolayer-identifiers.md
- Resources: resources.md
- Troubleshooting: troubleshooting.md
# ------- configuration properties ---------------
# Use Material theme
# - installation notes:  https://github.com/squidfunk/mkdocs-material
theme: material
# Don't enable the repo URL because irritating edit icons are shown when editing really isn't allowed
#repo_url:  https://github.com/OpenWaterFoundation/owf-app-geoprocessor-python-doc-user
site_description:  Open Water Foundation Learn GeoProcessor
site_author:  Open Water Foundation
site_favicon:  'images/OWF-Logo-Favicon-32x32.png'
copyright:  Copyright Open Water Foundation
# Use extra CSS to customize styles, based on theme
extra_css:
  - 'css/extra-material-theme.css'
markdown_extensions:
  - footnotes
